name: GitHub Top Languages

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update README with Top Languages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Generate Top Languages Card
        run: node index.js
      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Updated README with Top Languages'
          git push
